### ISSUE TITLE
Creating a subject does not propagate the email address to the underlying user

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/ManagementPortal#76]
Creating a subject in the project view also triggers the creation of a user. However the email address supplied does not propagate to the user. This results in updates on the user causing errors, since the email is required. E.g. trying to activate a user that has no associated email address results in an internal server error.

The email address should propagate from the created subject to the created user.

**Comment by nivemaham** [comment]
This is not an issue. It is a feature. We cannot save an email address related to a subject as it is a person identifiable information. The reason for having email currently, is to get a link to reset their password. It is expected when the QRCode generation is finalized, the subject is activated when you request an access-token for the first-time or can be activated by default. The way to activate a subject as of a current design is to reset the password from password reset link. I assume you are encountering this because you are running MP without an smtp running and properly configured.

**Comment by dennyverbeeck** [comment]
> This is not an issue. It is a feature.

:smile: Very true

Apparently the test server was not running the latest version from dev branch, i can't reproduce this locally on the latest version. Closing this issue and i'll open another one for the default activation of users related to subjects.

**Comment by nivemaham** [comment]
Indeed. That should be the next step.
