### ISSUE TITLE
User API design: use login

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/ManagementPortal#81]
For the API design of users and subjects, it would help to use the `login` property as a path parameter everywhere instead of `id`, since the `login` is encoded in the JWT and `id` is not. I understand it is already set to be unique, possibly it would also need an index?

**Comment by nivemaham** [comment]
Valid request. We can indeed change the apis to use `login` instead of `id`. The apis with `id` are used in MP front-end and it is also the default jhipster apis. The apis used by external clients uses `login`. But i agree that it could be reduced to just apis with `login`. It shouldn't be difficult to change the apis for `User` and `Subject`. What should be the priority for this issue? Should we complete this for the October? We have a milestone planned for October 6th. @dennyverbeeck , @blootsvoets

**Comment by dennyverbeeck** [comment]
I also think it makes a lot of sense. IMO we should work to get this in before the milestone, so we limit the changes to the API as much as possible afterwards.
